// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PlantOrganizer.Api.Data;

#nullable disable

namespace PlantOrganizer.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006103526_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("PlantOrganizer.Api.Models.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DaysToHarvest")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LatinName")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("MinPotVolumeLiters")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("SunRequirement")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WateringIntervalDays")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Plants");
                });
#pragma warning restore 612, 618
        }
    }
}
